name: Compartir datos entre jobs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/wpm-api/WisdomPetMedicine.sln
    - name: Build
      run: dotnet build src/wpm-api/WisdomPetMedicine.sln --no-restore
    - name: Test
      run: dotnet test src/wpm-api/WisdomPetMedicine.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish src/wpm-api/WisdomPetMedicine.sln --configuration Release --output publish
    - name: Subir datos
      uses: actions/upload-artifact@v3
      with:
        path: publish
  storage:
    name: Almacenamiento
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Descargar datos
      uses: actions/download-artifact@v3
      with:
        path: publish
    - name: Print the final result
      shell: bash
      run: ls publish
