name: Expresiones

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        dotnetversion: [6.0.x, 7.0.x]
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH: src/wpm-api/WisdomPetMedicine.sln
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnetversion }}
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build $SOLUTION_PATH --configuration ${{ matrix.configuration }} --no-restore
    - name: Versi√≥n
      run: echo ${{ matrix.dotnetversion }}
    - name: Pruebas unitarias
      run: dotnet test $SOLUTION_PATH
      if: ${{ contains('6.0', matrix.dotnetversion ) }}