name: GitHub Token

on:
  workflow_dispatch:

env:
  SOLUTION_PATH: src/wpm-api/WisdomPetMedicine.sln
  DOCKERFILE_PATH: src/wpm-api/WisdomPetMedicine.Api/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build $SOLUTION_PATH --no-restore
    - name: Test
      run: dotnet test $SOLUTION_PATH --no-build --verbosity normal
  docker:
    name: Contenerizaci√≥n con Docker y .NET
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build src/wpm-api --file $DOCKERFILE_PATH --tag rdiazconcha/github-actions-esencial:${{ github.run_number }}

    - uses: docker/login-action@v2
      name: Log in en Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: PASSWORDINCORRECTO

    - name: Crear un issue con el API REST
      if: ${{ failure() }}
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "No se puede autenticar con Docker Hub",
          "body": "Error en el workflow **${{ github.workflow }}**."
          }' \
        --fail