name: Ámbitos de variables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH: src/wpm-api/WisdomPetMedicine.sln
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build $SOLUTION_PATH --no-restore
    - name: Test
      run: dotnet test $SOLUTION_PATH --no-build --verbosity normal
  docker:
    name: Contenerización con Docker y .NET
    env:
      DOCKERFILE_PATH: src/wpm-api/WisdomPetMedicine.Api/Dockerfile
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build src/wpm-api --file $DOCKERFILE_PATH --tag github-action-esencial